apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client-deployment
spec:
  selector:
    matchLabels:
      app: my-client
  replicas: 2
  template:
    metadata:
      labels:
        app: my-client
    spec:
      containers:
        - name: my-client-pod
          image: my_client:local
          imagePullPolicy: Never
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-client-service
spec:
  selector:
    app: my-client
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
