apiVersion: apps/v1 #APIのバージョン
kind: Deployment #リソースの種類
metadata:
  name: "demo-server1-deployment"
spec:
  selector: #どのPodを起動するか
    matchLabels:
      app: demo-server1
  replicas: 1
  template: #作成されるPodのテンプレート
    metadata:
      labels:
        app: demo-server1
    spec:
      containers:
      - name: "demo-server1-pod"
        image: "localhost:5000/demo-server1:amd64"
        ports:
        - containerPort: 3000 #ポート番号
        startupProbe:
          httpGet:
            path: /healthy
            port: 3000
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthy
            port: 3000
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: "demo-server1-service"
spec:
  selector: #下記のLabel（ラベル）を指定したPodに伝送
    app: demo-server1
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30030
